name: apk-upload-workflow

on:
  push:
    branches: 
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: 1.8
    

    - name: Build with Gradle
      run: chmod +x gradlew && ./gradlew build check

    - name: Upload apk at webpage
      continue-on-error: true
      run: curl --max-time 1200 -F 'apk_file=@/home/runner/work/netra/netra/app/build/outputs/apk/debug/app-debug.apk' https://vitpunerobotics.com/cms1/mobileapk.php