name: build-workflow

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: 1.8
        
    - name: Build with Gradle
      run: chmod +x gradlew && ./gradlew build check


